# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TheatreInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('preformance', models.CharField(max_length=250)),
                ('places', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='customerrecord',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
