# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-03 09:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20170728_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerrecord',
            name='phone',
            field=models.CharField(max_length=15),
        ),
    ]
