# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-03 10:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20170803_1251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerrecord',
            name='id',
        ),
        migrations.AddField(
            model_name='customerorders',
            name='id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customerorders',
            name='phone',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='customerrecord',
            name='phone',
            field=models.CharField(max_length=15, primary_key=True, serialize=False),
        ),
    ]
