# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-03 10:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20170803_1306'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomerOrders',
        ),
    ]
