# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-03 11:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_auto_20170803_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerrecord',
            name='add_phone',
            field=models.CharField(max_length=15),
        ),
    ]
