# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-03 11:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_auto_20170803_1425'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerorders',
            name='places',
        ),
        migrations.RemoveField(
            model_name='customerorders',
            name='preformance',
        ),
        migrations.RemoveField(
            model_name='customerorders',
            name='price',
        ),
        migrations.AddField(
            model_name='customerorders',
            name='theatre_info',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='polls.TheatreInfo'),
            preserve_default=False,
        ),
    ]
