# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-09 17:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_auto_20170803_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='theatreinfo',
            name='customer',
            field=models.ForeignKey(default=99999999, on_delete=django.db.models.deletion.CASCADE, to='polls.CustomerRecord'),
            preserve_default=False,
        ),
    ]
