# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-09 17:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_theatreinfo_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theatreinfo',
            name='customer',
        ),
    ]
