# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-13 16:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0014_auto_20170813_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerrecord',
            name='orders',
            field=models.ManyToManyField(to='polls.TheatreInfo'),
        ),
    ]
